In [ ]:
#inclass activity 02/11/2020 for DATA3401

In [ ]:
#setdiff = pd.concat([dat1,dat2]).drop_duplicates(keep = False) 
#(find duplicate and drop out the duplicate, mtcar is the original file)
#from Ipython.core.interactiveshell import Shell
#InteractiveShell.ast_node_interactivity = "all"
#use for run all code result, not the last one or print

In [4]:
# readin CSV file in pandas
import pandas as pd
import os #find the path
path = os.getcwd()
path

'/Users/nhile/Desktop/DATA3401/Week 5'

In [5]:
file1 = pd.read_csv("~/Desktop/DATA3401/Week 5/file1.dms")
file1

,carname,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,375.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [7]:
set_diff = pd.concat([dat1,dat2,dat3,dat4]).drop_duplicates(keep = False)
set_diff

NameError: name 'dat1' is not defined

In [3]:
file2 = pd.read_csv("~/Desktop/DATA3401/Week 5/file2.dms", sep = ';', header = None)
file2

,0,1,2,3,4,5,6,7,8,9,10,11
0,carname,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
1,Mazda RX4,21,6,160,110,3.9,2.62,16.46,0,1,4,4
2,Mazda RX4 Wag,21,6,160,110,3.9,2.875,17.02,0,1,4,4
3,Datsun 710,22.8,4,108,93,3.85,2.32,18.66,1,1,4,1
4,Hornet 4 Drive,21.4,6,258,110,3.08,3.215,19.44,1,0,3,1
5,Hornet Sportabout,18.7,8,360,175,3.15,3.44,17.02,0,0,3,2
6,Valiant,18.1,6,225,105,2.76,3.46,20.22,1,0,3,1
7,Duster 360,14.3,8,360,245,3.21,3.57,15.84,0,0,3,4
8,Merc 240D,24.4,4,146.7,62,3.69,3.19,20,1,0,4,2
9,Merc 230,22.8,4,140.8,95,3.92,3.15,22.9,1,0,4,2
10,Merc 280,19.2,6,167.6,123,3.92,3.44,18.3,1,0,4,4
11,Merc 280C,17.8,6,167.6,123,3.92,3.44,18.9,1,0,4,4
12,Merc 450SE,16.4,8,275.8,180,3.07,4.07,17.4,0,0,3,3
13,Merc 450SL,17.3,8,275.8,180,3.07,3.73,17.6,0,0,3,3
14,Merc 450SLC,15.2,8,275.8,180,3.07,3.78,18,0,0,3,3
15,Cadillac Fleetwood,10.4,8,472,205,2.93,5.25,17.98,0,0,3,4
16,Lincoln Continental,10.4,8,460,215,3,5.424,17.82,0,0,3,4
17,Chrysler Imperial,14.7,8,440,230,3.23,5.345,17.42,0,0,3,4
18,Fiat 128,32.4,4,78.7,66,4.08,2.2,19.47,1,1,4,1
19,Fiat X1-9,27.3,4,79,66,4.08,1.935,18.9,1,1,4,1
20,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
21,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.9,1,1,4,1
22,Toyota Corona,21.5,4,120.1,97,3.7,2.465,20.01,1,0,3,1
23,Dodge Challenger,15.5,8,318,150,2.76,3.52,16.87,0,0,3,2
24,AMC Javelin,15.2,8,304,150,3.15,3.435,17.3,0,0,3,2
25,Camaro Z28,13.3,8,350,245,3.73,3.84,15.41,0,0,3,4
26,Pontiac Firebird,19.2,8,400,175,3.08,3.845,17.05,0,0,3,2
27,Fiat X1-9,27.3,4,79,66,4.08,1.935,18.9,1,1,4,1
28,Porsche 914-2,26,4,120.3,91,4.43,2.14,16.7,0,1,5,2
29,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.9,1,1,5,2
30,Ford Pantera L,15.8,8,351,264,4.22,3.17,14.5,0,1,5,4
31,Ferrari Dino,19.7,6,145,175,3.62,2.77,15.5,0,1,5,6
32,Maserati Bora,15,8,301,335,3.54,3.57,14.6,0,1,5,8
33,Volvo 142E,21.4,4,121,109,4.11,2.78,18.6,1,1,4,2

In [4]:
# we can use sep = tab-determinted
file3 = pd.read_csv("~/Desktop/DATA3401/Week 5/file3.dms", sep = '\t', header = None)
file3

,0,1,2,3,4,5,6,7,8,9,10,11
0,carname,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
1,Mazda RX4,21,6,160,110,3.9,2.62,16.46,0,1,4,4
2,Mazda RX4 Wag,21,6,160,110,3.9,2.875,17.02,0,1,4,4
3,Datsun 710,22.8,4,108,93,3.85,2.32,18.61,1,1,4,1
4,Hornet 4 Drive,21.4,6,258,110,3.08,3.215,19.44,1,0,3,1
5,Hornet Sportabout,18.7,8,360,175,3.15,3.44,17.02,0,0,3,2
6,Valiant,18.1,6,225,105,2.76,3.46,20.22,1,0,3,1
7,Duster 360,14.3,8,360,245,3.21,3.57,15.84,0,0,3,4
8,Merc 240D,24.4,4,146.7,62,3.69,3.19,20,1,0,4,2
9,Merc 230,22.8,4,140.8,95,3.92,3.15,22.9,1,0,4,2
10,Merc 280,19.2,6,167.6,123,3.92,3.44,18.3,1,0,4,4
11,Merc 280C,17.8,6,167.6,123,3.92,3.44,18.9,1,0,4,4
12,Merc 450SE,16.4,8,275.8,180,3.07,4.07,17.4,0,0,3,3
13,Merc 450SL,17.3,8,275.8,180,3.07,3.73,17.6,0,0,3,3
14,Merc 450SLC,15.2,8,275.8,180,3.07,3.78,18,0,0,3,3
15,Cadillac Fleetwood,10.4,8,472,205,2.93,5.25,17.98,0,0,3,4
16,Lincoln Continental,10.4,8,460,215,3,5.424,17.82,0,0,3,4
17,Chrysler Imperial,14.7,8,440,230,3.23,5.345,17.42,0,0,3,4
18,Fiat 128,32.4,4,78.7,66,4.08,2.2,19.47,1,1,4,1
19,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
20,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.9,1,1,4,1
21,Toyota Corona,21.5,4,120.1,97,3.7,2.465,20.01,1,0,3,1
22,Dodge Challenger,15.5,8,318,150,2.76,3.52,16.87,0,0,3,2
23,AMC Javelin,15.2,8,304,150,3.15,3.435,17.3,0,0,3,2
24,Camaro Z28,13.3,8,350,245,3.73,3.84,15.41,0,0,3,4
25,Pontiac Firebird,19.2,8,400,175,3.08,3.845,17.05,0,0,3,2
26,Porsche 914-2,26,4,120.3,91,4.43,2.14,16.7,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.9,1,1,5,2
28,Ford Pantera L,15.8,8,351,264,4.22,3.17,14.5,0,1,5,4
29,Ferrari Dino,19.7,6,145,175,3.62,2.77,15.5,0,1,5,6
30,Maserati Bora,15,8,301,335,3.54,3.57,14.6,0,1,5,8
31,Volvo 142E,21.4,4,121,109,4.11,2.78,18.6,1,1,4,2

In [5]:
#we can use space in sep = ' '
file4 = pd.read_csv("~/Desktop/DATA3401/Week 5/file4.dms", sep =' ')
file4

,carname,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,23.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,330.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,115.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,119.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,115.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [6]:
#import os
#path = os.getcwd()
#path

In [8]:
file5 = pd.read_excel("Desktop/DATA3401/Week 5/file5.xlsx", sheet_name = 1)
file5
 #sheet_name = 1 because it's count 0,1,2 in the excel file for python

FileNotFoundError: [Errno 2] No such file or directory: 'Desktop/DATA3401/Week 5/file5.xlsx'

In [39]:
#grass all sheet and combine them
# or we can use sheet_name = "file5data"
file_5 = pd.concat(pd.read_excel('Desktop/DATA3401/Week 5/file5.xlsx', sheet_name = [1]), ignore_index = True)
file_5

,carname,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
13,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
14,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
15,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
16,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
17,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
18,Toyota Corolla,23.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
19,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
20,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
21,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
22,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
23,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
24,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
25,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
26,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
27,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
28,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
29,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
30,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [ ]:
compare1 = dat1.mean()
min1 = dat1.min()
max1 = dat1.max()

print(compare1)
print(min1)
print(max1)